src/SGQ.Presentation.Site/Areas/Transparencia/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SGQ.Core.Domain.Command;
using SGQ.Crosscutting.Identity.Context;
using SGQ.Presentation.Site.Areas.Transparencia.Models;
using SGQ.Presentation.Site.Controllers;
using SGQ.Transparencia.Domain.Post.Command;

namespace SGQ.Presentation.Site.Areas.Transparencia.Controllers
{
    [Area("Transparencia")]
    [BreadCrumb(Title = "Atividade", UseDefaultRouteUrl = true, Order = 0)]
    public class PostController : BaseController
    {

        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;

        public PostController(IUserService userService, IConfiguration configuration, IMapper mapper) : base(userService)
        {
            _configuration = configuration;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var retorno = await GetAsync<List<PostViewModel>>($"{_configuration["apis-endpoints:transparencia"]}api/post");
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consulta o recurso solicitado.");
                retorno = new List<PostViewModel>();
            }

            var model = new IndexPostViewModel();
            model.Lista = retorno;

            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(IndexPostViewModel model)
        {
            var retorno = await GetAsync<List<PostViewModel>>($"{_configuration["apis-endpoints:transparencia"]}api/post?" + model.Filtro.UrlEncodedContent());
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consulta o recurso solicitado.");
                retorno = new List<PostViewModel>();
            }

            model.Lista = retorno;

            return View("Index", model);
        }

        [HttpGet]
        public async Task<IActionResult> Criar()
        {
            return View("CriarEditar", new PostViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Criar(PostViewModel model)
        {

            var retorno = new CommandResult<PostViewModel>();
            var command = _mapper.Map<PostCriarCommand>(model);
            retorno = await PostAsync<CommandResult<PostViewModel>>($"{_configuration["apis-endpoints:transparencia"]}api/Post", command);

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<PostViewModel>();
            }

            if (retorno.Valido == false)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, retorno.Retorno.codigo, "Código da Postagem", true);
                return RedirectToAction("Index");
            }

            return View("CriarEditar", model);
        }

        [HttpGet("Transparencia/{controller}/{action}/{codigo}")]
        public async Task<IActionResult> Alterar(string codigo)
        {

            var retorno = await GetAsync<PostViewModel>($"{_configuration["apis-endpoints:transparencia"]}api/Post/{codigo}");

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new PostViewModel();
            }

            return View("CriarEditar", retorno);

        }

        [HttpPost]
        public async Task<IActionResult> Alterar(PostViewModel model)
        {
            var retorno = new CommandResult<PostViewModel>();
            var command = _mapper.Map<PostAtualizarCommand>(model);
            retorno = await PutAsync<CommandResult<PostViewModel>>($"{_configuration["apis-endpoints:transparencia"]}api/Post/{model.codigo}", command);

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<PostViewModel>();
            }

            if (retorno.Valido == false)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, "Postagem alterada com sucesso!");
                return RedirectToAction("Index");
            }

            return View("CriarEditar", model);
        }

        [AllowAnonymous]
        [HttpGet("Transparencia/{controller}/{action}/feed.{format}"), FormatFilter]
        public async Task<IActionResult> Feeds()
        {
            
            var feed = new rss();
            feed.channel = new rssChannel();
            feed.channel.title = "Divulgação e Transparência";
            feed.channel.description = "Divulgação e Transparência";
           
            var retorno = await GetAsync<List<PostViewModel>>($"{_configuration["apis-endpoints:transparencia"]}api/post?publico=true");
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consulta o recurso solicitado.");
                retorno = new List<PostViewModel>();
            }

            //List<feedEntry> entries = new List<feedEntry>();
            var items = new List<rssChannelItem>();
            foreach (var item in retorno)
            {
                items.Add(new rssChannelItem()
                {
                    title = item.titulo,
                    creator = "Editor",
                    description = item.descricao,
                    category= new string[] { "Transparencia" },
                    pubDate = item.modificadoEm.ToString(),
                    content = new content() { medium=item.conteudo, url= $"http://localhost:44322/Transparencia/Post/visualizar?codigo={item.codigo}" },
                    guid = new rssChannelItemGuid() { isPermaLink=true, Value="" },
                    link = $"http://localhost:44322/Transparencia/Post/view?codigo={item.codigo}"
                });
            }

            feed.channel.item = items.ToArray();

            return Ok(feed);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Listar()
        {
            var retorno = await GetAsync<List<PostViewModel>>($"{_configuration["apis-endpoints:transparencia"]}api/Post?publico=true");

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new List<PostViewModel>();
            }

            return View(retorno);
        }

        [AllowAnonymous]
        [HttpGet("Transparencia/{controller}/{action}/{codigo}")]
        public async Task<IActionResult> Visualizar(string codigo)
        {
            var retorno = await GetAsync<PostViewModel>($"{_configuration["apis-endpoints:transparencia"]}api/Post/{codigo}");

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new PostViewModel();
            }

            return View(retorno);
        }
    }
}

src/SGQ.Presentation.Site/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.ModelBinding
@using Microsoft.CodeAnalysis

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SGQ.Presentation.Site</title>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
              integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
              crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.min.css" rel="stylesheet" integrity="sha384-uhut8PejFZO8994oEgm/ZfAv0mW1/b83nczZzSwElbeILxwkN491YQXsCFTE6+nx" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<header>
    
    <partial name="_navbar" />
    
</header>
<div class="container-fluid">
    
    
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SGQ - Sistema de Gestão da Qualidade - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/SGQ.Presentation.Site/Views/Shared/_breadcrumbs.cshtml
<!--
@Html.ActionLink("Home", "Index", "Home")
@if(ViewContext.RouteData.Values["controller"].ToString() != "Home") {
    @:> @Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index", ViewContext.RouteData.Values["controller"].ToString())
}
@if(ViewContext.RouteData.Values["action"].ToString() != "Index"){
    @:> @Html.ActionLink(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["controller"].ToString())
}
-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Library</a></li>
        <li class="breadcrumb-item active" aria-current="page">Data</li>
    </ol>
</nav>

src/SGQ.Presentation.Site/Views/Shared/_messages.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding
@using SGQ.Presentation.Site.Controllers;
@using Newtonsoft.Json
@if (!(TempData["Messages"] is null))
{
    var items = JsonConvert.DeserializeObject<List<dynamic>>(TempData["Messages"].ToString());
    var icone = "";
    foreach (var item in items)
    {
        switch (item["type"].ToString())
        {
            case "success": icone = "fa-check-circle"; break;
            case "danger": icone = "fa-times-circle"; break;
            case "info": icone = "fa-info-circle"; break;
            case "warning": icone = "fa-exclamation-triangle"; break;
            default:
                icone = "fa-check-circle"; break;
        }

        <div class="alert alert-@item.type alert-dismissible fade show" role="alert">
            <strong> <i class="fa @icone mr-2" aria-hidden="true"></i> </strong> @item.message
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

@if (!(TempData["ModalMessages"] is null))
{
    var items = JsonConvert.DeserializeObject<List<dynamic>>(TempData["ModalMessages"].ToString());
    foreach (var item in items)
    {
        <div class="modal fade" id="modalMessage" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h3 class="text-@item.type.ToString().ToUpper()">@item.message</h3>
                        <p>@item.submessage</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript"> $(document).ready(function() {  $('#modalMessage').modal('show')  }); </script>
    }
}

src/SGQ.Presentation.Site/Views/Shared/_navbar.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http
@using Microsoft.CodeAnalysis
@addTagHelper *, DNTBreadCrumb.Core
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    var user = this.User.FindFirstValue(ClaimTypes.Name);
}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom mb-0">
    <div class="navbar-brand" onclick="prompt('Token', token.Data.token)">SGQ</div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active"> <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> </li>

            @if (user != null)
            {
                <li class="nav-item dropdown">
                    <span class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Incidentes
                    </span>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-area="Incidentes" asp-controller="Incidente" asp-action="Index">Incidentes</a>
                        <a class="dropdown-item" asp-area="Incidentes" asp-controller="Problema" asp-action="Index">Problemas</a>
                        <a class="dropdown-item" asp-area="Incidentes" asp-controller="NC" asp-action="Index"> Não Conformidades</a>
                    </div>
                </li>
            }

            @if (user != null)
            {
                <li class="nav-item dropdown">
                    <span class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Processos
                    </span>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-area="Processos" asp-controller="Processo" asp-action="Index">Processos</a>
                    </div>
                </li>
            }

            <li class="nav-item dropdown">
                <span class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Transparência
                </span>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    @if (user is null)
                    {
                        <a class="dropdown-item" asp-area="Transparencia" asp-controller="Post" asp-action="Listar">Lista de Postagens</a>
                    }
                    else
                    {
                        <a class="dropdown-item" asp-area="Transparencia" asp-controller="Post" asp-action="Listar">Lista de Postagens</a>
                        <a class="dropdown-item" asp-area="Transparencia" asp-controller="Post" asp-action="Index">Postagem</a>
                    }
                </div>
            </li>

        </ul>



        <div class="form-inline my-2 my-lg-0">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> @( @user ?? "Login" )
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        @if (user is null)
                        {
                            <a class="dropdown-item" asp-area="Seguranca" asp-controller="Autenticacao" asp-action="Login">Login</a>
                        }
                        else
                        {
                            <a class="dropdown-item" asp-area="Seguranca" asp-controller="Autenticacao" asp-action="Perfil">Perfil</a>
                            <a class="dropdown-item" asp-area="Seguranca" asp-controller="Autenticacao" asp-action="Logout">Logout</a>
                        }
                    </div>
                </li>
            </ul>
        </div>
        <div class="form-inline my-2 my-lg-0 ml-3">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" style="">
                    <a href="/Transparencia/Post/Feeds/feed.xml" style="color: orange !important;font-size: 18px;" title="rss">
                        <i class="fa fa-rss-square" aria-hidden="true"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<nav>

    <breadcrumb asp-homepage-title="Home"
                class="breadcrumb shadow-sm p-3 mb-3 bg-light"
                asp-homepage-url="@Url.Action("Index", "Home", values: new { area = "" })"
                asp-bootstrap-version="V4"
                asp-homepage-glyphicon="fa fa-home"></breadcrumb>
</nav>