src/SGQ.Presentation.Site/Areas/Incidentes/Controllers/IncidenteController.cs
using AutoMapper;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SGQ.Core.Domain.Command;
using SGQ.Crosscutting.Identity.Context;
using SGQ.Incidentes.Domain.Incidente.Command;
using SGQ.Presentation.Site.Areas.Incidentes.Models;
using SGQ.Presentation.Site.Controllers;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SGQ.Presentation.Site.Areas.Incidentes.Controllers
{
    [Authorize]
    [Area("Incidentes")]
    [BreadCrumb(Title = "Incidentes", UseDefaultRouteUrl = true, Order = 0)]
    public class IncidenteController : BaseController
    {
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;

        public IncidenteController(IUserService userService, IConfiguration configuration, IMapper mapper) : base(userService)
        {
            _configuration = configuration;
            _mapper = mapper;
        }

        [HttpGet]
        [BreadCrumb(Title = "Home", Order = 1)]
        public async Task<IActionResult> Home()
        {
            return View("Home");
        }


        [HttpGet]
        [BreadCrumb(Title = "Index", Order = 1)]
        public async Task<IActionResult> Index()
        {
            var retorno = await GetAsync<List<IncidenteViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/Incidente");
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consultar os incidentes.");
                retorno = new List<IncidenteViewModel>();
            }

            var model = new IndexIncidentesViewModel();
            model.Lista = retorno;

            var retornoSumarizado = await GetAsync<List<SumarizadoViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/sumarizado/Incidente");
            if (retornoSumarizado == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consultar os incidentes.");
                retornoSumarizado = new List<SumarizadoViewModel>();
            }
            ViewBag.sumarizado = retornoSumarizado;

            return View("Index", model);
        }

        [HttpPost("Incidentes/{controller}/{action}")]
        public async Task<IActionResult> Index(IndexIncidentesViewModel model)
        {

            var retorno = await GetAsync<List<IncidenteViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/Incidente?" + model.Filtro.UrlEncodedContent());
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consultar os incidentes.");
                retorno = new List<IncidenteViewModel>();
            }

            model.Lista = retorno;

            var retornoSumarizado = await GetAsync<List<SumarizadoViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/sumarizado/Incidente");
            if (retornoSumarizado == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consultar os incidentes.");
                retornoSumarizado = new List<SumarizadoViewModel>();
            }
            ViewBag.sumarizado = retornoSumarizado;

            return View("Index", model);
        }

        [HttpGet("Incidentes/{controller}/{action}")]
        [BreadCrumb(Title = "Criar", Order = 2)]
        public async Task<IActionResult> Criar()
        {
            return View("CriarEditar", new IncidenteViewModel());
        }


        [HttpPost("Incidentes/{controller}/{action}")]
        public async Task<IActionResult> Criar([FromForm] IncidenteViewModel value)
        {
            var retorno = new CommandResult<IncidenteViewModel>();
            var command = _mapper.Map<IncidenteCriarCommand>(value);
            retorno = await PostAsync<CommandResult<IncidenteViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/Incidente", command);

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<IncidenteViewModel>();
            }

            if (retorno.Valido == false)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, retorno.Retorno.codigo, "Código do Incidente", true);
                return RedirectToAction("Index");
            }


            return View("CriarEditar", value);

        }

        [HttpGet("Incidentes/{controller}/{action}/{codigo?}")]
        [BreadCrumb(Title = "Alterar", Order = 2)]
        public async Task<IActionResult> Alterar(string codigo)
        {
            var retorno = await GetAsync<IncidenteViewModel>($"{_configuration["apis-endpoints:incidentes"]}api/Incidente/{codigo}");

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new IncidenteViewModel();
            }
            
            return View("CriarEditar", retorno);
        }

        [HttpPost("Incidentes/{controller}/{action}/{codigo?}")]
        public async Task<IActionResult> Alterar(string codigo, [FromForm] IncidenteViewModel value)
        {
            var retorno = new CommandResult<IncidenteViewModel>();
            var command = _mapper.Map<IncidenteAtualizarCommand>(value);
            retorno = await PutAsync<CommandResult<IncidenteViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/Incidente/{value.codigo}", command);

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<IncidenteViewModel>();
            }

            if (retorno.Valido == false)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, "Incidente atualizado com sucesso!");
                return RedirectToAction("Index");
            }


            return View("CriarEditar", value);

        }

        [HttpGet("Incidentes/{controller}/{action}/{codigo?}")]
        public async Task<IActionResult> Excluir([FromRoute] string codigo)
        {
            var retorno = await DeleteAsync<CommandResult<bool>>($"{_configuration["apis-endpoints:incidentes"]}api/Incidente/{codigo}");
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<bool>();
            }

            if (!retorno.Retorno)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, "Registro excluido com sucesso!");
            }

            return RedirectToAction("Index");
        }

        [HttpPost("Incidentes/{controller}/{action}")]
        public async Task<IActionResult> FecharIncidente([FromForm] IncidenteViewModel value)
        {
            var retorno = new CommandResult<bool>();
            var command = _mapper.Map<IncidenteFecharCommand>(value);
            retorno = await PostAsync<CommandResult<bool>>($"{_configuration["apis-endpoints:incidentes"]}api/Incidente/{value.codigo}/Fechar", command);

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<bool>();
            }

            if (retorno.Valido == false)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, "Incidente fechado com sucesso!");
                return RedirectToAction("Index");
            }


            return View("CriarEditar", value);

        }

    }

}

src/SGQ.Presentation.Site/Areas/Incidentes/Controllers/IncidentesHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Mvc;

namespace SGQ.Presentation.Site.Areas.Incidentes.Controllers
{
    [Area("Incidentes")]
    [BreadCrumb(Title = "Incidentes", UseDefaultRouteUrl = true, Order = 0)]
    public class IncidentesHomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SGQ.Presentation.Site/Areas/Incidentes/Controllers/NCController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Configuration;
using SGQ.Core.Domain.Command;
using SGQ.Incidentes.Domain.Incidente.Command;
using SGQ.Presentation.Site.Areas.Incidentes.Models;
using SGQ.Presentation.Site.Controllers;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using SGQ.Crosscutting.Identity.Context;
using SGQ.Incidentes.Domain.NaoConformidade.Command;
using SGQ.Incidentes.Domain.NC.Command;

namespace SGQ.Presentation.Site.Areas.Incidentes.Controllers
{
    [Authorize]
    [Area("Incidentes")]
    [BreadCrumb(Title = "Não Conformidades", UseDefaultRouteUrl = true, Order = 0)]
    public class NCController : BaseController
    {
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;

        public NCController(IUserService userService, IConfiguration configuration, IMapper mapper) : base(userService)
        {
            _configuration = configuration;
            _mapper = mapper;
        }
        

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var retorno = await GetAsync<List<NCViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/NaoConformidade");
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consultar as não conformidades.");
                retorno = new List<NCViewModel>();
            }

            var model = new IndexNCViewModel();
            model.Lista = retorno;

            return View("Index", model);
        }

        [HttpPost("Incidentes/{controller}/{action}")]
        public async Task<IActionResult> Index(IndexNCViewModel model)
        {

            var retorno = await GetAsync<List<NCViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/NaoConformidade?" + model.Filtro.UrlEncodedContent());
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível consultar as não conformidades.");
                retorno = new List<NCViewModel>();
            }

            model.Lista = retorno;

            return View("Index", model);
        }

        [HttpGet]
        public IActionResult Criar()
        {
            return View("CriarEditar", new NCViewModel());
        }

        [HttpPost("Incidentes/{controller}/{action}")]
        public async Task<IActionResult> Criar([FromForm] NCViewModel value)
        {
            var retorno = new CommandResult<NCViewModel>();

            var command = _mapper.Map<NaoConformidadeCriarCommand>(value);
            retorno = await PostAsync<CommandResult<NCViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/NaoConformidade", command);
            
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<NCViewModel>();
                retorno.Valido = false;
            }
            
            if (!retorno.Valido)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, retorno.Retorno.codigo, "Codigo da Não Conformidade.", true);
                return RedirectToAction("Index", "NC", new { area = "Incidentes" });
            }

            return View("CriarEditar", value);
        }

        [HttpGet("Incidentes/{controller}/{action}/{codigo?}")]
        public async Task<IActionResult> Alterar(string codigo)
        {
            var retorno = await GetAsync<NCViewModel>($"{_configuration["apis-endpoints:incidentes"]}api/NaoConformidade/{codigo}");

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new NCViewModel();
            }

            return View("CriarEditar", retorno);
        }

        [HttpPost("Incidentes/{controller}/{action}")]
        public async Task<IActionResult> Alterar([FromForm] NCViewModel value)
        {
            var retorno = new CommandResult<NCViewModel>();

            var command = _mapper.Map<NaoConformidadeAtualizarCommand>(value);
            retorno = await PutAsync<CommandResult<NCViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/NaoConformidade/"+value.codigo, command);

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<NCViewModel>();
                retorno.Valido = false;
            }

            if (!retorno.Valido)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, "Registro salvo com sucesso!");
                return RedirectToAction("Index", "NC", new { area = "Incidentes" });
            }

            return View("CriarEditar", value);
        }

        [HttpGet("Incidentes/{controller}/{action}/{codigo?}")]
        public async Task<IActionResult> Excluir([FromRoute] string codigo)
        {
            var retorno = await DeleteAsync<CommandResult<bool>>($"{_configuration["apis-endpoints:incidentes"]}api/NaoConformidade/{codigo}");
            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<bool>();
            }

            if (!retorno.Retorno)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, "Registro excluido com sucesso!");
            }

            return RedirectToAction("Index");
        }

        [HttpPost("Incidentes/{controller}/{action}/{codigo?}")]
        public async Task<IActionResult> Fechar([FromRoute] string codigo, [FromForm] NCViewModel value)
        {
            var command = _mapper.Map<NaoConformidadeFecharCommand>(value);
            var retorno = await PostAsync<CommandResult<NCViewModel>>($"{_configuration["apis-endpoints:incidentes"]}api/NaoConformidade/" + codigo + "/Fechar", command);

            if (retorno == null)
            {
                ModelState.AddModelError("Consulta", "Não foi possível acessar o recurso solicitado.");
                retorno = new CommandResult<NCViewModel>();
            }

            if (retorno.Valido == false)
            {
                foreach (var item in retorno.Erros)
                {
                    ModelState.AddModelError(item.Key, item.Message);
                }
            }
            else
            {
                ShowMessage(EnumMessageType.success, "Registro alterado com sucesso!");
                return RedirectToAction("Index");
            }

            return View("CriarEditar", value);
        }

    }

}

src/SGQ.Presentation.Site/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Mvc;
using SGQ.Presentation.Site.Models;

namespace SGQ.Presentation.Site.Controllers
{
    [BreadCrumb(Title = "Home", UseDefaultRouteUrl = true, Order = 0)]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SGQ.Presentation.Site/Areas/Incidentes/Views/Incidente/CriarEditar.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model SGQ.Presentation.Site.Areas.Incidentes.Models.IncidenteViewModel

@{
    ViewData["Title"] = "Criar";
    Layout = "_Layout";
    var acao = Model.codigo is null ? "Criar" : "Alterar";
}

<h1 class="display-4">Incidente</h1>
<p>Incidente @Model.codigo</p>

<partial name="_messages" />

<div class="card">
    <div class="card-body">
        <form asp-area="Incidentes" asp-controller="Incidente" asp-action="@acao" method="post">

            <div class="form-group">
                <label asp-for="codigo"></label>
                <input asp-for="codigo" class="form-control" readonly="readonly" />
                <span asp-validation-for="titulo" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="status"></label>
                <input asp-for="status" class="form-control" readonly="readonly" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="titulo"></label>
                <input asp-for="titulo" class="form-control" />
                <span asp-validation-for="titulo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="descricao"></label>
                <textarea  rows="5" asp-for="descricao" class="form-control"></textarea>
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="estadoRegistro" />

            <button type="submit" class="btn btn-primary">Salvar</button>

        </form>
    </div>
</div>

@if (Model.codigo != null)
{
    <div class="card mt-4">
        <div class="card-body">
            <form asp-area="Incidentes" asp-controller="Incidente" asp-action="FecharIncidente" method="post">

                <input type="hidden" asp-for="codigo"/>

                <div class="form-group">
                    <label asp-for="solucao"></label>
                    <textarea rows="5" asp-for="solucao" class="form-control" readonly="@(Model.codigo is null)"></textarea>
                    <span asp-validation-for="solucao" class="text-danger"></span>
                </div>


                <button type="submit" class="btn btn-primary">Fechar Incidente</button>

            </form>
        </div>
    </div>
}

src/SGQ.Presentation.Site/Areas/Incidentes/Views/Incidente/Home.cshtml
@{
    ViewData["Title"] = "Home";
}

<h1>Home</h1>

src/SGQ.Presentation.Site/Areas/Incidentes/Views/Incidente/Index.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding
@using SGQ.Presentation.Site.Areas.Incidentes.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model SGQ.Presentation.Site.Areas.Incidentes.Models.IndexIncidentesViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var sumarizado = (IEnumerable<SumarizadoViewModel>) ViewBag.sumarizado;
}

<h1 class="display-4">Incidentes</h1>
<p>Lista de Incidentes</p>

<partial name="_messages" />

<div class="row">
    <div class="col-md-2">
        <div class="card text-white bg-danger mb-3">
            <div class="card-header">Incidentes abertos</div>
            <div class="card-body">
                <h3 class="card-title">@( sumarizado.FirstOrDefault(x => x.status == "Aberto")?.count) Incidente(s)</h3>
            </div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card text-white bg-success mb-3">
            <div class="card-header">Incidentes fechados</div>
            <div class="card-body">
                <h3 class="card-title">@( sumarizado.FirstOrDefault(x => x.status == "Fechado")?.count) Incidente(s)</h3>
            </div>
        </div>
    </div>
</div>


<div class="card col-md-12" style="background:#f5f5dc">
    <div class="card-block">
        <p class="ml-3 mt-3">Pesquisar por Incidente</p>
        <div class="card-body m-0 p-0">
            <form asp-area="Incidentes" asp-controller="Incidente" asp-action="Index" method="post">

                <div class="col-md-12">
                    <div class="row">
                        <div class="form-group col-md-3">
                            <input asp-for="Filtro.codigo" class="form-control form-control-sm" placeholder="Codigo" />
                            <span asp-validation-for="Filtro.codigo" class="text-danger"></span>
                        </div>

                        <div class="form-group col-md-3">
                            <input asp-for="Filtro.titulo" class="form-control form-control-sm" placeholder="Título" />
                            <span asp-validation-for="Filtro.titulo" class="text-danger"></span>
                        </div>

                        <div class="form-group col-md-3">
                            <input asp-for="Filtro.status" class="form-control form-control-sm" placeholder="Status" />
                            <span asp-validation-for="Filtro.status" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-3">
                            <button type="submit" class="btn btn-sm btn-primary"> Filtrar registros</button>
                        </div>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>
<div class="card mt-3 rounded-0 shadow-sm">
    <div class="card-header text-right">
        <a class="btn btn-sm btn-primary" asp-area="Incidentes" asp-action="Criar" asp-controller="Incidente"> Criar Incidente </a>
    </div>
    <div class="table-responsive">
        <table class="table table-sm table-hover table-bordered table-striped rounded-0 mb-0">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>Titulo</th>
                    <th>Descrição</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @if (Model.Lista.Any() == false)
                {
                    <tr>
                        <td colspan="5"> Nenhum item encontrado. </td>
                    </tr>
                }

                @foreach (var item in Model.Lista)
                {
                    <tr>
                        <td width="50"> <span title="@item.codigo"> @item.codigo </span> </td>
                        <td>@item.titulo</td>
                        <td>@item.descricao</td>
                        <td width="100">@item.status</td>
                        <td width="100">
                            <div class="btn-group text-center" role="group">

                                <a style="width: 40px;" data-toggle="tooltip" data-placement="left" title="Alterar" asp-area="Incidentes" asp-controller="Incidente" asp-action="Alterar" asp-route-codigo="@item.codigo">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </a>
                                <a style="width: 40px;" data-toggle="tooltip" data-placement="left" title="Excluir" onclick="if (confirm('Deseja realmente excluir o registro?')) window.location='/Incidentes/Incidente/Excluir/@item.codigo';">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>

                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer text-muted">
        (@Model.Lista.Count) Registros encontrados
    </div>
</div>